--  require '技能.野怪光环.BOSS-专注光环'
--  require '技能.野怪光环.BOSS-吸血光环'
--  require '技能.野怪光环.BOSS-命令光环'
--  require '技能.野怪光环.BOSS-耐久光环'
--  require '技能.野怪光环.BOSS-恢复光环'
 require '技能.野怪光环.减速光环'
 require '技能.野怪光环.沉默光环'
