-- require "技能.英雄技能.阿尔塞斯天赋"
-- require "技能.英雄技能.山丘王天赋"
-- require "技能.英雄技能.剑圣天赋"
-- require "技能.英雄技能.希尔瓦娜斯天赋"
-- require "技能.英雄技能.吉安娜天赋"
-- require "技能.英雄技能.炼金术士天赋"
require "技能.英雄技能.万箭齐发"
require "技能.英雄技能.交叉闪电"
require "技能.英雄技能.闪电链"
require "技能.英雄技能.阳光枪"
require "技能.英雄技能.回旋刃"
require "技能.英雄技能.巨浪"
require "技能.英雄技能.御甲"
require "技能.英雄技能.炎爆术"
require "技能.英雄技能.暴风雪"
require "技能.英雄技能.火焰雨"
require "技能.英雄技能.风暴之力"
require "技能.英雄技能.飞焰"
require "技能.英雄技能.雷霆之剑"
require "技能.英雄技能.空间之力"
require "技能.英雄技能.天罗地网"
require "技能.英雄技能.血焰神脂"
require "技能.英雄技能.神威"
require "技能.英雄技能.强化后的神威"
require "技能.英雄技能.刀刃旋风"
require "技能.英雄技能.强化后的刀刃旋风"
require "技能.英雄技能.痛苦尖叫"
require "技能.英雄技能.强化后的痛苦尖叫"
require "技能.英雄技能.死亡脉冲"
require "技能.英雄技能.强化后的死亡脉冲"
require "技能.英雄技能.践踏"
require "技能.英雄技能.强化后的践踏"
require "技能.英雄技能.穿刺"
require "技能.英雄技能.强化后的穿刺"
require "技能.英雄技能.水舞"
require "技能.英雄技能.强化后的水舞"
require "技能.英雄技能.缠绕"
require "技能.英雄技能.强化后的缠绕"
require "技能.英雄技能.疾步风"
require "技能.英雄技能.强化后的疾步风"
require "技能.英雄技能.神圣护甲"
require "技能.英雄技能.强化后的神圣护甲"
require "技能.英雄技能.不灭佛隐"
require "技能.英雄技能.强化后的不灭佛隐"
require "技能.英雄技能.血雾神隐"
require "技能.英雄技能.绝对领域"
require "技能.英雄技能.招架之力"
require "技能.英雄技能.强化后的招架之力"
require "技能.英雄技能.水疗术"
require "技能.英雄技能.强化后的水疗术"
require "技能.英雄技能.生生不息"
require "技能.英雄技能.硬化皮肤"
require "技能.英雄技能.闪避"
require "技能.英雄技能.财富"
require "技能.英雄技能.贪婪者的心愿"
require "技能.英雄技能.龙凤佛杀"
require "技能.英雄技能.凰燃天成"
require "技能.英雄技能.狂龙爆"
require "技能.英雄技能.强化后的狂龙爆"
require "技能.英雄技能.红莲爆"
require "技能.英雄技能.强化后的红莲爆"
require "技能.英雄技能.暴击"
require "技能.英雄技能.渡业妖爆"
require "技能.英雄技能.强化后的渡业妖爆"
require "技能.英雄技能.技暴"
require "技能.英雄技能.蚀魂魔舞"
require "技能.英雄技能.强化后的蚀魂魔舞"
require "技能.英雄技能.赤焰魔舞"
require "技能.英雄技能.望远镜"
require "技能.英雄技能.剑空破"
require "技能.英雄技能.吸血鬼"
require "技能.英雄技能.分裂伤害"
require "技能.英雄技能.嗜血术"
require "技能.英雄技能.碧涛妖变"
require "技能.英雄技能.邪灵变"
require "技能.英雄技能.暗之领域"
require "技能.英雄技能.强化后的暗之领域"
require "技能.英雄技能.迷之领域"
require "技能.英雄技能.强化后的迷之领域"

require "技能.英雄技能.审判之剑"
require "技能.英雄技能.憎恶"
require "技能.英雄技能.强化后的憎恶"
require "技能.英雄技能.X射线"
require "技能.英雄技能.强化后的X射线"
require "技能.英雄技能.剑刃风暴"
require "技能.英雄技能.强化后的剑刃风暴"

require "技能.英雄技能.星落"
require "技能.英雄技能.强化后的星落"

require "技能.英雄技能.群体风暴之锤"

require "技能.英雄技能.火力全开"
require "技能.英雄技能.火力支援"
require "技能.英雄技能.强化后的火力支援"

require "技能.英雄技能.反甲"
-- require "技能.英雄技能.蝗虫群"
require "技能.英雄技能.群星陨落"
