require '技能.通用buff'
require '技能.通用技能'
require '技能.野怪技能'
-- require '技能.野怪光环'
require '技能.英雄技能'
require '技能.成就'
require '技能.新光环'
require '技能.技能事件'
require '技能.技能总览'
require '技能.异火'
require '技能.技能羁绊'
require '技能.buff'