require 'ui.client.util'
require 'ui.client.actor'
require 'ui.client.sendmsg'
require 'ui.client.tip'
-- require 'ui.client.kzt'
require 'ui.client.提示框'
require 'ui.client.控制台'
require 'ui.client.英雄属性'
require 'ui.client.存档信息'
require 'ui.client.属性面板'

-- require 'ui.client.操作栏'
-- require 'ui.client.属性面板'
-- require 'ui.client.英雄排行榜'
-- require 'ui.client.伤害排行榜'
-- require 'ui.client.选择信使面板'
-- require 'ui.client.技能列表'
-- require 'ui.client.战报'
-- require 'ui.client.棋子图鉴'
-- require 'ui.client.动画'
-- require 'ui.client.放置棋子'
require 'ui.client.菜单'
require 'ui.client.全屏提醒'
-- require 'ui.client.排行榜'