
require '技能.野怪技能.BOSS技能.毁灭'
-- require '技能.野怪技能.BOSS技能.崎岖外表'
require '技能.野怪技能.BOSS技能.地狱火雨'
require '技能.野怪技能.BOSS技能.超强力量'
require '技能.野怪技能.BOSS技能.产卵'
require '技能.野怪技能.BOSS技能.激光'
require '技能.野怪技能.BOSS技能.暗影冲刺'
require '技能.野怪技能.BOSS技能.龙破斩'
require '技能.野怪技能.BOSS技能.撕裂大地'
require '技能.野怪技能.BOSS技能.洪流'
require '技能.野怪技能.BOSS技能.雷击'
require '技能.野怪技能.BOSS技能.大地震'
require '技能.野怪技能.BOSS技能.暗能源'
require '技能.野怪技能.BOSS技能.骚灵'
require '技能.野怪技能.BOSS技能.魔力之枷'
-- require '技能.野怪技能.BOSS技能.神圣之光'
require '技能.野怪技能.BOSS技能.火刑'
-- require '技能.野怪技能.BOSS技能.极度饥渴'
require '技能.野怪技能.BOSS技能.血之祭祀'
-- require '技能.野怪技能.BOSS技能.法力流失'
require '技能.野怪技能.BOSS技能.超新星'
-- require '技能.野怪技能.BOSS技能.分裂箭'

require '技能.野怪技能.BOSS技能.无敌'
require '技能.野怪技能.BOSS技能.伤害守卫'
require '技能.野怪技能.BOSS技能.boss光子灵枪'
require '技能.野怪技能.BOSS技能.酒桶'
